<?php
require_once("action/SignInAction.php");

$action = new SignInAction();

$action->execute();
require_once("partial/Header.php");
?>
 <div class="mainHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 clearfix">
	  
        <h1>Legal</h1>
		<p></p>
      </div>
    </div>
  </div>
</div>

<div id="privacy" class="container">

  
  <div class="sectionbody">
    <div class="sectionbody-full">

        <h3>A Note from the Team</h3>
        
        <p>We created this website as a university project. We do ask that you treat our service and community with respect<p>
        <h3>Accepting the Terms of Service</h3>

        <p>This website is a site and other applications for questions and answers<p>
		<h3>1. Access to the Services</h3>

        <p>Subject to the terms and conditions of this Agreement, website may offer to provide the Services, as described more fully on the Network, and which are selected by Subscriber, solely for Subscribers<p>
        <p>Subscriber certifies to website that Subscriber is an individual ) at least 13 years of age. No one under the age of 13 may provide any personal information to or on website (including, for example, a name, address, telephone number or email address). Subscriber also certifies that they are legally permitted to use the Services and access the Network, and takes full responsibility for the selection and use of the Services and access of the Network.<p>
		
        <p>website will use reasonable efforts to ensure that the Network and Services are available twenty-four hours a day, seven days a week.<p>
        <p>You agree that neither website nor the Network will be liable in any event to You or any other party for any suspension, modification, discontinuance or lack of availability of the Network, the service, any Subscriber Content, or other Content.</p>

        <p>This website retains the right to create limits on use and storage in its sole discretion at any time with or without notice.</p>

        <p>Subscriber shall be responsible for obtaining and maintaining any equipment or ancillary services needed to connect to, access the Network or otherwise use the Services, including, without limitation, modems, hardware, software, and long distance or local telephone service.<p>
		
        <h3>2. Content</h3>

        <p>The Network and its contents are intended solely for the use of the Network Subscribers and may only be used in accordance with the terms of this Agreement. <p>
		
        
        <p>All trademarks, service marks, and trade names are proprietary to website and/or third parties. Subscriber shall abide by all copyright notices, information, and restrictions contained in any Content accessed through the Services.</p>

        <p>This website is protected by copyright as a collective work and/or compilation, pursuant canadian government copyright laws, international conventions, and other copyright laws.<p>
		
        <p>Subscriber may download or copy the Content, and other items displayed on the Network for download, for personal use, provided that Subscriber maintains all copyright and other notices contained in such Content.</p>

        
        <p>Any other downloading, copying, or storing any Content (other than Subscriber Content or Profile Content that is available via the website API) for other than personal, noncommercial use is expressly prohibited without prior written permission from website, or from the copyright holder identified in such Content's copyright notice. In the event You download software from the Network (other than Subscriber Content or Profile Content that is available via the website API), the software, including any files, images incorporated in or generated by the software, and the data accompanying the software (collectively, the &ldquo;Software&rdquo;) is licensed to You by website or third party licensors for Your personal, noncommercial use, and no title to the Software shall be transferred to You. website or third party licensors retain full and complete title to the Software and all intellectual property rights therein.</p>


        <p>You agree that all Subscriber Content that You contribute to the Network is perpetually and irrevocably licensed to this website<p>
		
		
		<h3>3. Restrictions</h3>

        <p>Subscriber is responsible for all of its activity in connection with the Services and accessing the Network. <p>
        <p>Use of the Network or Services to violate the security of any computer network, crack passwords or security encryption codes, transfer or store illegal material including that are deemed threatening or obscene, or engage in any kind of illegal activity is expressly prohibited. Under no circumstances will Subscriber use the Network or the Service to (a) send unsolicited e-mails, bulk mail, spam or other materials to users of the Network or any other individual, (b) harass, threaten, stalk or abuse any person or party, including other users of the Network, (c) create a false identity or to impersonate another person, or (d) knowingly post any false, inaccurate or incomplete material, or (e) copy, download, or scrape any Personal Profile Content for the purpose of indexing software engineers, social recruiting, sourcing, employment-related services, compiling databases of employment solicitation targets, providing content for a hiring platform without the express permission of website or the User.</p>

        

        <h3>4. Warranty disclaimer</h3>

        <p> Subscriber acknowledges that website has no control over, and no duty to take any action regarding: which users gains access to the Network; which Content Subscriber accesses via the Network; what effects the Content may have on Subscriber; how Subscriber may interpret or use the Content; or what actions Subscriber may take as a result of having been exposed to the Content. Much of the Content of the Network is provided by and is the responsibility of the user or subscriber who posted the Content. website does not monitor the Content of the Network and takes no responsibility for such Content. Subscriber releases website from all liability for Subscriber having acquired or not acquired Content through the Network. The Network may contain, or direct Subscriber to sites containing, information that some people may find offensive or inappropriate. website makes no representations concerning any content contained in or accessed through the Network, and website will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the Network.</p>

        <p>This website will make reasonable efforts to store and preserve the material residing on the Network, neither website nor the Network is responsible or liable in any way for the failure to store, preserve or access Subscriber Content or other materials you transmit or archive on the Network. You are strongly urged to take measures to preserve copies of any data, material, content or information you post or upload on the Network.</p>

        <p>The Services, Content, Network and any Software are provided on an "as is" basis, without warranties of any kind, either express or implied, including, without limitation, implied warranties of merchantability, fitness for a particular purpose or non-infringement. website makes no representations or warranties of any kind with respect to the Network, the Services, including any representation or warranty that the use of the Network or Services will (a) be timely, uninterrupted or error-free or operate in combination with any other hardware, software, system or data, (b) meet your requirements or expectations, (c) be free from errors or that defects will be corrected, (d) be free of viruses or other harmful components.</p>

        <p>This website disclaims any liability or responsibility for the accuracy, reliability, availability, completeness, legality or operability of the material or services provided on this Network. By using this Network, you acknowledge that website is not responsible or liable for any harm resulting from (1) use of the Network; (2) downloading information contained on the Network including but not limited to downloads of content posted by subscribers; (3) unauthorized disclosure of images, information or data that results from the upload, download or storage of content posted by subscribers; (4) the temporary or permanent inability to access or retrieve any Subscriber Content from the Network, including, without limitation, harm caused by viruses, worms, trojan horses, or any similar contamination or destructive program.</p>
		<p>Thank you!</p>
    </div>

</div>
<?php
require_once("partial/Footer.php");
